name: Documentation Improvements
description: Suggest improvements to the documentation.
labels: ["documentation"]
assignees:
  - foobar-doc-assignee-dev
body:
  - type: textarea
    id: freeform
    attributes:
      label: Describe the Request
      description: >
        Please describe limitations of the current documentation or
        suggested improvements.
    validations:
      required: true
