# This workflow just verifies that the docs build without any
# warnings (as configured in the tox recipe). This is only run on
# the test-me-* branches and PRs as pushes to main will trigger the docs
# workflow.
name: check-docs

on:
  push:
    branches: [test-me-*]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-docs:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-python: true

      - name: Build docs with tox
        run: uv run tox -e docs
